import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          "lang": "ع",
          "feature_not_enable": "this device not support finger print",
          "welcome_page": "============Welcome Page=============",
          "store_on_internet": "Store on internet",
          "lets_shopping": "Lets shopping",
          "create_account": "Create Account",
          "login_page": "============Login Page=============",
          "welcome": "Welcome",
          "please_login_to_your_account": "Please login to your account",
          "email_or_phone_number": "Email or phone number",
          "password": "Password",
          "forget_password": "Forget password?",
          "register_new": "Register new?",
          "login": "Login",
          "or": "Or",
          "first_name": "First name",
          "last_name": "Last name",
          "facebook": "Facebook",
          "google": "Google",
          "email_or_phone": "Email or phone",
          "signup_page": "============Signup Page=============",
          "username": "Username",
          "email": "Email",
          "phone_number": "Phone number",
          "confirm_password": "Confirm password",
          "upload_photo": "Upload photo",
          "register_new_account": "Register new account",
          "register": "Register",
          "signup_t1": "By clicking register you agree to the following ",
          "signup_t2": "Terms and Conditions ",
          "signup_t3": "without reservation",
          "required": "Required",
          "invalid_phone_number": "Invalid phone number",
          "invalid_email_address": "Invalid email address",
          "permission_denied": "Permission denied",
          "error": "Error",
          "done": "Done",
          "weak_password": "Weak password",
          "not_match": "Not match",
          "choose_an_image": "Choose an image",
          "please_provide_the_location_coordinates":
              "Please provide the location coordinates",
          "open_gps": "Open GPS",
          "pick_location": "Pick Location",
          "location_picked": "Location Picked",
          "location_coordinates": "Location coordinates",
          "forget_password_page":
              "============Forget Password Page=============",
          "are_you_forget_your_password": "Are you forget your password",
          "forget_password_msg":
              "Type your phone number and we will send you a code to verify",
          "submit": "Submit",
          "next": "Next",
          "verify_code": "Verify Code",
          "verify_msg":
              "Please enter the code sent to your mobile phone number via SMS",
          "rest_password_page": "============Reset Password Page=============",
          "create_new_password": "Create New Password",
          "rest_password_msg": "We sent an OTP to your phone number",
          "code": "Code",
          "new_password": "New Password",
          "reset_password_msg": "You can now set a new password",
          "home_page": "============Home Page=============",
          "hi": "Hi ",
          "search_by_id": "Search by ID",
          "search_by_name": "Search by Name",
          "new_orders": "New orders",
          "ongoing_orders": "Ongoing orders",
          "delivery": "Delivery",
          "online_paid": "Online Paid",
          "minutes": "minutes",
          "id": "ID",
          "customer_amount": "Customer amount",
          "price": "price",
          "eg": "RAS",
          "customer_name": "Customer name",
          "shop_location": "Shop location",
          "customer_location": "Customer location",
          "price_type": "Price type",
          "shop_owner_amount": "Shop owner amount",
          "deny": "Deny",
          "accept": "Accept",
          "whole_whole_sale": "Whole whole sale",
          "whole_sale": "Whole sale",
          "sizes": "Sizes",
          "colors": "Colors",
          "sale": "Sale",
          "no_colors_available": "No colors available",
          "no_sizes_available": "No sizes available",
          "order_details_page": "============Order Details Page=============",
          "customer_number": "Customer number",
          "shop_owner_name": "Shop owner name",
          "owner_number": "Owner number",
          "pickup": "Pickup",
          "distance": "Distance",
          "estimate": "Estimate",
          "drop_off": "Drop off",
          "delivered": "Delivered",
          "add_new_order_page": "============Add New Order Page=============",
          "add_customer_location": "Add customer location",
          "add_shop_location": "Add shop location",
          "items": "Items",
          "add_item": "Add Item",
          "add_location": "Add Location",
          "add_new_order": "Add new order",
          "search_for_product": "Search for product",
          "add": "Add",
          "drawer_page": "============Drawer=============",
          "edit_profile": "Edit Profile",
          "change_language": "Language",
          "clients_info": "Clients",
          "home_page_title": "Home Page",
          "show_all_products": "Show All Products",
          "attend_and_leave": "Attend and leave",
          "edit_profile_page": "============Edit Profile Page=============",
          "edit_profile_page_title": "Edit Profile",
          "all_clients_page": "============All Clients Page=============",
          "all_clients_page_title": "Clients",
          "all_clients_page_name": "Name",
          "all_clients_page_dept": "Dept",
          "all_clients_page_add": "Add",
          "attendance_page": "============Attendance Page=============",
          "attendance_page_attend": "Attend",
          "attendance_page_leave": "Leave",
          "attendance_page_note": "Note",
          "attendance_page_register": "Register",
          "attendance_page_msg": "Please Select Attend or Leave",
          "all_clients_of_representative_page":
              "============All Clients of Representative Page=============",
          "all_clients_of_representative_page_title": "Your Clients",
          "all_clients_of_representative_page_add_client": "Add Client",
          "add_client": "Add Client",
          "my_History_page": "============My History Page=============",
          "my_History_page_title": "My History",
          "my_History_page_date": "Date",
          "my_History_page_status": "Status",
          "my_History_page_notes": "Notes",
          "show_products_page": "============Products Page=============",
          "show_products_page_title": "Products",
          "show_products_by_rating": "By Rating",
          "show_products_without_rating": "Without Rating",
          "show_products_filtering": "Filter",
          "show_products_quantity": "Quantity",
          "product_page": "============Product Page=============",
          "product_page_desc": "Description",
          "product_page_sizes": "Sizes",
          "product_page_colors": "Colors",
          "product_page_Wholesale_wholesale_price": "Wholesale wholesale price",
          "product_page_quantity": "Quantity",
          "product_page_Wholesale_price": "Wholesale price",
          "product_Selling_price": "Selling price",
          "product_barcode": "Barcode",
          "set_dept_page": "============Set Dept Page=============",
          "set_dept_page_title": "Debt settlement",
          "set_dept_page_subtraction": "Subtraction",
          "set_dept_page_addition": "Addition",
          "set_dept_page_amount": "Amount",
          "quantity_error": "cannot add this product with 0 quantity",
          "hours": "hours",
          "days": "days",
          "printer_settings": "printer settings",
          "print_order": "print order",
          "invoice": "invoice",
          "tax1": "tax",
          "tax2": "delivery charges",
          "discount": "discount",
          "total": "total",
          "sub_total": "sub total",
          "edit_order": "edit order",
          "check_in": "check in",
          "check_out": "check out",
          "order_updated_succes": "order updated succefully"
        },
        'ar': {
          "lang": "EN",
          "feature_not_enable": "هذا الجهاز لا يدعم البصمة",
          "check_in": "دخول",
          "check_out": "خروج",
          "welcome_page": "============Welcome Page=============",
          "store_on_internet": "متجر علي الانترنت",
          "lets_shopping": "دعونا نتسوق معا",
          "create_account": "انشاء حساب",
          "login_page": "============Login Page=============",
          "welcome": "اهلا بك",
          "please_login_to_your_account": "من فضلك سجل الدخول الي حسابك",
          "email_or_phone_number": "البريد الالكتروني او رقم الهاتف",
          "password": "كلمه المرور",
          "forget_password": "نسيت كلمه المرور؟",
          "register_new": "تسجيل جديد؟",
          "login": "تسجيل الدخول",
          "or": "او",
          "first_name": "الاسم الاول",
          "last_name": "الاسم الاخير",
          "facebook": "فيسبوك",
          "google": "جوجل",
          "email_or_phone": "البريد الالكتروني او رقم الهاتف",
          "signup_page": "============Signup Page=============",
          "username": "اسم المستخدم",
          "email": "البريد الالكتروني",
          "phone_number": "رقم الهاتف",
          "confirm_password": "تاكيد كلمه المرور",
          "upload_photo": "رفع صوره",
          "register_new_account": "تسجيل حساب جديد",
          "register": "تسجيل",
          "signup_t1": "بالضغط على تسجيل أنت توافق على ",
          "signup_t2": "الأحكام والشروط ",
          "signup_t3": "بدون حجز",
          "forget_password_page":
              "============Forget Password Page=============",
          "are_you_forget_your_password": "هل نسيت كلمة المرور الخاصة بك",
          "forget_password_msg": "اكتب رقم هاتفك وسنرسل لك رمزًا للتحقق",
          "submit": "تاكيد",
          "next": "التالي",
          "price_type": "نوع السعر",
          "whole_whole_sale": "جملة الجملة",
          "whole_sale": "جملة",
          "sale": "قطاعي",
          "sizes": "الاحجام",
          "colors": "الالوان",
          "no_colors_available": "لا توجد الوان متوفره",
          "no_sizes_available": "لا توجد احجام متوفرة",
          "verify_code": "رمز التاكيد",
          "verify_msg":
              "الرجاء ادخال الرمز المرسل الي رقم هاتفك المحمول عبر الرسائل القصيرة",
          "rest_password_page": "============Reset Password Page=============",
          "create_new_password": "إنشاء كلمة مرور جديدة",
          "rest_password_msg": "لقد أرسلنا رمز تحقق إلى رقم هاتفك",
          "code": "الكود",
          "new_password": "كلمة المرور الجديدة",
          "reset_password_msg": "يمكنك الان تعيين كلمه مرور جديدة",
          "home_page": "============Home Page=============",
          "hi": "اهلا ",
          "search_by_id": "بحث بكود الطلب",
          "search_by_name": "بحث بالاسم",
          "new_orders": "الطلبات الجديدة",
          "ongoing_orders": "الطلبات المنتهية",
          "delivery": "توصيل",
          "online_paid": "الدفع الكتروني",
          "minutes": "دقيقة",
          "id": "الكود",
          "customer_amount": "اجمالي الفاتورة",
          "price": "السعر",
          "eg": "ريال",
          "customer_name": "اسم العميل",
          "shop_location": "موقع المتجر",
          "customer_location": "موقع العميل",
          "shop_owner_amount": "مبلغ صاحب المحل",
          "deny": "رفض",
          "accept": "قبول",
          "required": "مطلوب",
          "invalid_phone_number": "رقم هاتف غير صحيح",
          "invalid_email_address": "بريد الكتروني غير صالح",
          "permission_denied": "تم رفض التصريح",
          "error": "خطا",
          "done": "تم",
          "weak_password": "كلمة مرور ضعيفة",
          "not_match": "غير متطابق",
          "choose_an_image": "اختر صورة",
          "please_provide_the_location_coordinates": "قم بتحدد احداثيات الموقع",
          "open_gps": "قم بفتح محدد المواقع",
          "pick_location": "اخذ احداثيات الموقع",
          "location_picked": "تم الحصول علي احداثيات الموقع",
          "location_coordinates": "احداثيات الموقع",
          "order_details_page": "============Order Details Page=============",
          "customer_number": "هاتف العميل",
          "shop_owner_name": "اسم صاحب المحل",
          "owner_number": "هاتف صاحب المحل",
          "pickup": "التقاط",
          "distance": "المسافه",
          "estimate": "الوقت",
          "drop_off": "اسقاط",
          "delivered": "تم التسليم",
          "add_new_order_page": "============Add New Order Page=============",
          "add_customer_location": "أضف موقع العميل",
          "add_shop_location": "أضف موقع المتجر",
          "items": "العناصر",
          "add_item": "اضافه عنصر",
          "add_location": "اضافه الموقع",
          "add_new_order": "أضف طلب جديد",
          "search_for_product": "ابحث عن المنتج",
          "add": "اضف",
          "drawer_page": "============Drawer=============",
          "edit_profile": "تعديل البروفايل",
          "change_language": "تغيير اللغة",
          "clients_info": "العملاء",
          "home_page_title": "الصفحة الرئيسية",
          "show_all_products": "عرض جميع المنتجات",
          "attend_and_leave": "حضور وانصراف",
          "edit_profile_page": "============Edit Profile Page=============",
          "edit_profile_page_title": "تعديل الصفحة الشخصية",
          "all_clients_page": "============All Clients Page=============",
          "all_clients_page_title": "العملاء",
          "all_clients_page_name": "الاسم",
          "all_clients_page_dept": "المديونية",
          "all_clients_page_add": "اضافة",
          "my_History_page": "============My History Page=============",
          "my_History_page_title": "السجل الخاص بك",
          "my_History_page_date": "التاريخ",
          "my_History_page_status": "الحالة",
          "my_History_page_notes": "ملاحظات",
          "attendance_page": "============Attendance Page=============",
          "attendance_page_attend": "حضور",
          "attendance_page_leave": "انصراف",
          "attendance_page_note": "ملاحظة",
          "attendance_page_register": "تسجيل",
          "attendance_page_msg": "من فضلك اختر حضور أو انصراف",
          "all_clients_of_representative_page":
              "============All Clients of Representative Page=============",
          "all_clients_of_representative_page_title": "قائمة عملائك",
          "all_clients_of_representative_page_add_client": "اضافة عميل",
          "add_client": "اضافة عميل",
          "show_products_page": "============Products Page=============",
          "show_products_page_title": "المنتجات",
          "show_products_by_rating": "أعلى تقييم",
          "show_products_without_rating": "بدون تقييم",
          "show_products_filtering": "فلترة",
          "show_products_quantity": "الكمية",
          "product_page": "============Product Page=============",
          "product_page_desc": "الوصف",
          "product_page_sizes": "المقاسات",
          "product_page_colors": "الألوان",
          "product_page_Wholesale_wholesale_price": "سعر جملة الجملة",
          "product_page_quantity": "الكمية",
          "product_page_Wholesale_price": "سعر الجملة",
          "product_Selling_price": "سعر البيع",
          "product_barcode": "باركود",
          "set_dept_page": "============Set Dept Page=============",
          "set_dept_page_title": "تسوية المديونية",
          "set_dept_page_subtraction": "تسوية",
          "set_dept_page_addition": "اضافة",
          "set_dept_page_amount": "المبلغ",
          "quantity_error": "لا يمكن إضافة هذا المنتج الكمية 0",
          "hours": "ساعة",
          "days": "يوم",
          "printer_settings": "اعدادات الطباعة",
          "print_order": "طباعة الطلب",
          "invoice": "فاتورة",
          "tax1": "الضريبة",
          "tax2": "ضريبة التوصيل",
          "discount": "الخصم",
          "total": "الاجمالي",
          "sub_total": "المجموع الفرعي",
          "edit_order": "تعديل الطلب",
          "order_updated_succes": "تم تعديل الطلب بنجاح"
        }
      };
}
